### ISSUE TITLE
Finish README

### ISSUE THREAD

**Issue by yuuuuty** [yuuuuty/hello-world#1]
README作成！

**Comment by yuuuuty** [comment]
@dice Do you  hava any ideas for how to fix this?

**Comment by dice** [comment]
@yuuuuty :fireworks:

**Comment by yuuuuty** [comment]
@dice Thank you !
Github lecture class was very fun and studied very much !
I want this lecture class to do on different form once again !

**Comment by dice** [comment]
@yuuuuty Awesome! Thank you for attending today.
